import React from 'react';
import "./About.css";

class About extends React.Component {
    handleClick = () => {
        this.props.toggle()
    }
    render() {
      return <div><span className="close" onClick={this.handleClick}>&times;    </span>
      <div className="about">
           
 <h3 className="toph3">About:</h3>
 <p> Conway's Game of Life is a zero-player game.
 Interact with the Game of Life by creating an
 initial configuration and observing how it evolves!</p>


  <h3>Rules:</h3>
  <ol> 
  <li>Any live cell with two or three live neighbours survives.</li>
 <li>Any dead cell with exactly three live neighbours becomes a live cell.</li>
 <li>All other live cells die in the next generation. (Similarly, all other dead cells stay dead.)</li>
 </ol>

 
 <h3>Instructions:</h3>
 <p>Tap or click grid cells to toggle cells between live and dead.</p>
 <p>Use Refresh Frequency (ms) slider to control playback speed</p>
 <p>Use Population Size slider to set live cells generated by Seed</p>
 <p>Click Clear to clear and reset the board</p>
 <p>Click Seed to reset the board and add live cells</p>
 <p>Click Run to start simulation</p>
 <p>Click Stop to pause simulation(only available if running)</p>
      </div>
      </div>;
    }
  }

export default About